<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMessages($value){
        return $this->createQueryBuilder('u')
            ->andWhere("t.emeteur = :val OR t.recepteur = :val")
            ->setParameter('val', $value)
            ->getQuery()
            ->getResult();
    }
}
