<?php

namespace AppBundle\Repository;


/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTickets($value){
        return $this->createQueryBuilder('t')
            ->andWhere("t.emeteur = :val OR t.recepteur = :val")
            ->setParameter('val', $value)
            ->getQuery()
            ->getResult();
    }
}
