<?php

namespace AppBundle\Repository;

/**
 * TypeproduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeproduitRepository extends \Doctrine\ORM\EntityRepository
{
}
