app_typeproduit:
    resource: "@AppBundle/Controller/TypeproduitController.php"
    type:     annotation

app_categorie:
    resource: "@AppBundle/Controller/CategorieController.php"
    type:     annotation

app_produit:
    resource: "@AppBundle/Controller/ProduitController.php"
    type:     annotation

app_ticket:
    resource: "@AppBundle/Controller/TicketController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /