article_homepage:
    path:     /
    defaults: { _controller: ArticleBundle:Default:index }
AjouterArticle:
    path:     /AjouterArticle
    defaults: { _controller: ArticleBundle:Default:AjouterArticle}
AfficherArticle:
    path:     /AfficherArticle
    defaults: { _controller: ArticleBundle:Default:AfficherArticle}
SupprimerArticle:
    path:     /SupprimerArticle {id}
    defaults: { _controller: ArticleBundle:Default:SupprimerArticle}
ModifierArticle:
    path:     /ModifierArticle/{id}
    defaults: { _controller: ArticleBundle:Default:ModifierArticle}

Article:
    path: /Article/{id}
    defaults: { _controller: ArticleBundle:Default:Article, id: null }
    requirements:
        id: .*



Nbvue:
     path:     /Nbvue {id}
     defaults: { _controller: ArticleBundle:Default:Nbvue}

SupprimerCommentaire:
    path:     /SupprimerCommentaire {id}
    defaults: { _controller: ArticleBundle:Default:SupprimerCommentaire}

ModifierCommentaire:
    path:     /ModifierCommentaire/{id}
    defaults: { _controller: ArticleBundle:Default:ModifierCommentaire}

MesArticles:
    path:     /MesArticles
    defaults: { _controller: ArticleBundle:Default:MesArticles}

AdminAfficherArticle:
    path:     /AdminAfficherArticle
    defaults: { _controller: ArticleBundle:Default:AdminAfficherArticle}
AdminSupprimerArticle:
    path:     /AdminSupprimerArticle {id}
    defaults: { _controller: ArticleBundle:Default:AdminSupprimerArticle}
AdminArticle:
    path: /AdminArticle/{id}
    defaults: { _controller: ArticleBundle:Default:AdminArticle, id: null }
    requirements:
        id: .*
AdminSupprimerCommentaire:
    path:     /AdminSupprimerCommentaire {id}
    defaults: { _controller: ArticleBundle:Default:AdminSupprimerCommentaire}